logger:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    app:
      level: DEBUG
      handlers: [console]
      propagate: false
  root:
    level: INFO
    handlers: [console]

jwt_handler:
  algorithm: "RS256"
  access_token_expire_minutes: 10
  refresh_token_expire_minutes: 20160 # 14 days
