services:
  app:
    build: ./
    env_file: ./.env
    ports:
      - "8001:8001"
    volumes:
      - ./src/migrations/versions:/app/src/migrations/versions
    depends_on:
      - database

  database:
    image: postgres:12
    container_name: database
    hostname: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
